# Create Heatmaps for Weather Parameters

In [1]:
# Import dependencies
import pandas as pd
import gmaps
import requests
from config import g_key

In [2]:
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kampot,KH,2021-02-04 19:09:25,10.6167,104.1833,75.20,88,20,2.30
1,1,Barrow,US,2021-02-04 19:09:26,71.2906,-156.7887,-23.80,76,1,3.44
2,2,North Bend,US,2021-02-04 19:05:08,43.4065,-124.2243,46.40,76,1,4.61
3,3,San Cristobal,VE,2021-02-04 19:09:26,7.7669,-72.2250,89.60,48,20,13.80
4,4,Havre-Saint-Pierre,CA,2021-02-04 19:09:27,50.2334,-63.5986,35.60,93,90,8.05
...,...,...,...,...,...,...,...,...,...,...
549,549,Skala,PL,2021-02-04 19:13:54,50.2305,19.8536,35.60,87,75,3.44
550,550,Mazyr,BY,2021-02-04 19:13:54,52.0495,29.2456,24.58,95,100,18.25
551,551,San Policarpo,PH,2021-02-04 19:13:55,12.1791,125.5072,79.68,85,95,16.78
552,552,Glencoe,ZA,2021-02-04 19:13:56,-28.1783,30.1470,63.97,89,100,3.69
553,553,Itumba,TZ,2021-02-04 19:13:56,-9.4000,33.1833,63.72,90,100,3.40

In [3]:
# Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use my Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# # Heatmap of temperature
# # Get the latitude and longitude.
# locations = city_data_df[["Lat", "Lng"]]

# # Get the maximum temperature.
# max_temp = city_data_df["Max Temp"]

# # Assign the figure variable
# fig = gmaps.figure()

# # Assign the heatmap variable
# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

# # Add the heatmap layer.
# fig.add_layer(heat_layer)

# # Call the figure to plot the data
# fig

In [10]:
# Above Google heatmaps does not plot negative numbers. To remove negative temperatures, use for loop
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# temps = []
# for temp in max_temp:
#     temps.append(max(temp, 0))

# Assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5) # Adjusting heatmap zoom by adding the geographic center of Earth and zoom

# Assign the heatmap variable
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4) # replaced
# the for loop with a list comprehension

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Percent Humidity Heatmap

In [12]:
# Heatmap for humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Percent Cloudiness Heatmap

In [14]:
# Heatmap for cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

## Create a Wind Speed Heatmap

In [15]:
# Heatmap for wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

# Get Vacation Criteria

In [18]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [19]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kampot,KH,2021-02-04 19:09:25,10.6167,104.1833,75.20,88,20,2.30
3,3,San Cristobal,VE,2021-02-04 19:09:26,7.7669,-72.2250,89.60,48,20,13.80
8,8,Puerto Ayora,EC,2021-02-04 19:09:29,-0.7393,-90.3518,86.00,62,0,5.75
13,13,Alwaye,IN,2021-02-04 19:09:32,10.1167,76.3500,77.00,78,0,2.30
14,14,Rikitea,PF,2021-02-04 19:09:32,-23.1203,-134.9692,78.30,69,75,10.76
17,17,Atuona,PF,2021-02-04 19:09:33,-9.8000,-139.0333,78.39,70,80,11.07
23,23,Saint-Philippe,RE,2021-02-04 19:09:37,-21.3585,55.7679,80.60,69,0,2.30
27,27,Puerto Colombia,CO,2021-02-04 19:06:21,10.9878,-74.9547,87.80,62,20,11.50
28,28,Sambava,MG,2021-02-04 19:09:38,-14.2667,50.1667,78.17,86,70,6.02
30,30,Hambantota,LK,2021-02-04 19:09:40,6.1241,81.1185,75.20,88,0,6.91

In [23]:
preferred_cities_df.count()

City_ID       170
City          170
Country       169
Date          170
Lat           170
Lng           170
Max Temp      170
Humidity      170
Cloudiness    170
Wind Speed    170
dtype: int64

# Map Vacation Criteria

In [24]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
0            Kampot      KH     75.20  10.6167  104.1833
3     San Cristobal      VE     89.60   7.7669  -72.2250
8      Puerto Ayora      EC     86.00  -0.7393  -90.3518
13           Alwaye      IN     77.00  10.1167   76.3500
14          Rikitea      PF     78.30 -23.1203 -134.9692
17           Atuona      PF     78.39  -9.8000 -139.0333
23   Saint-Philippe      RE     80.60 -21.3585   55.7679
27  Puerto Colombia      CO     87.80  10.9878  -74.9547
28          Sambava      MG     78.17 -14.2667   50.1667
30       Hambantota      LK     75.20   6.1241   81.1185

## Retrieve Hotels from a Nearby Search

In [27]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to locatio key for the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [28]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kampot,KH,75.20,10.6167,104.1833,Two Moons Hotel
3,San Cristobal,VE,89.60,7.7669,-72.2250,Pirineos
8,Puerto Ayora,EC,86.00,-0.7393,-90.3518,Castillo Galapagos
13,Alwaye,IN,77.00,10.1167,76.3500,Hotel Airlink Castle
14,Rikitea,PF,78.30,-23.1203,-134.9692,Pension Maro'i
17,Atuona,PF,78.39,-9.8000,-139.0333,Villa Enata
23,Saint-Philippe,RE,80.60,-21.3585,55.7679,"Chambres d'hÃ´te ""La TrinitÃ©"""
27,Puerto Colombia,CO,87.80,10.9878,-74.9547,Hotel El Emigrante
28,Sambava,MG,78.17,-14.2667,50.1667,Melrose
30,Hambantota,LK,75.20,6.1241,81.1185,Bungalow 63

## Create a Maximum temp heatmap from hotel_df

In [36]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

# Add markers for each city on top of heatmap. Source: https://jupyter-gmaps.readthedocs.io/en/latest/tutorial.html#markers-and-symbols
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))